stages:
  - build
  - test
  - sonarcloud-check

build_project:
  stage: build
  tags: [gradle]
  script:
    - echo "Build starting..."
  #  - gradle build

run_tests:
  stage: test
  tags: [gradle]
  script:
    - echo "Running tests..."
 #  - gradle test

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
sonarcloud-check:
  stage: sonarcloud-check
  tags: [gradle]
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner