stages:
  - build
  - test
  - sonarcloud-check

build_project:
  stage: build
  tags: [gradle]
  script:
    - echo "Build starting.."

test_job1:
  stage: test
  script:
    - echo "This job tests something"

test_job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."

sonarcloud_check:
  stage: sonarcloud-check
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - commit
    - master
    - develop
    - main
