stages:
  - install-commands
  - build
  - test
  - sonarcloud-check

variables:
  JAVA_HOME: "/tmp/java/jdk-21"  # Use temporary directories for pipeline jobs
  PATH: "$JAVA_HOME/bin:/tmp/gradle/gradle-7.4.2/bin:/tmp/sonar-scanner/sonar-scanner-4.7.0.2747-windows/bin:$PATH"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  GIT_STRATEGY: none

check_gitVersion:
  stage: install-commands
  tags: [gradle]
  script:
    - echo "Skipping Git operations due to strategy 'none'"

build_project:
  stage: build
  tags: [gradle]
  before_script:
    - cd $CI_PROJECT_DIR  # Ensure we are in the project directory
  script:
    - gradle clean build

run_tests:
  stage: test
  tags: [gradle]
  before_script:
    - cd $CI_PROJECT_DIR  # Ensure we are in the project directory
  script:
    - gradle test

sonarcloud-check:
  stage: sonarcloud-check
  tags: [gradle]
  before_script:
    - cd $CI_PROJECT_DIR  # Ensure we are in the project directory
  script:
    - gradle sonarqube