stages:
  - install-commands
  - build
  - test
  - sonarcloud-check

variables:
  PATH: "$CI_PROJECT_DIR/tools/gradle/gradle-7.4.2/bin:$CI_PROJECT_DIR/tools/sonar-scanner/sonar-scanner-4.7.0.2747-windows/bin:$PATH"

install_dependencies:
  stage: install-commands
  script:
    - mkdir -p $CI_PROJECT_DIR/tools
    - wget https://services.gradle.org/distributions/gradle-7.4.2-bin.zip -O gradle.zip
    - unzip gradle.zip -d $CI_PROJECT_DIR/tools/gradle
    - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-windows.zip -O sonar-scanner.zip
    - unzip sonar-scanner.zip -d $CI_PROJECT_DIR/tools/sonar-scanner
    - echo "Dependencies installed successfully in $CI_PROJECT_DIR/tools!"

build_project:
  stage: build
  before_script:
    - cd $CI_PROJECT_DIR
  script:
    - gradle clean build

run_tests:
  stage: test
  before_script:
    - cd $CI_PROJECT_DIR
  script:
    - gradle test

sonarcloud-check:
  stage: sonarcloud-check
  before_script:
    - cd $CI_PROJECT_DIR
  script:
    - sonar-scanner